### ISSUE TITLE
Would you mind to bring this to elm 0.19 ?

### ISSUE THREAD

**Issue by PixelPartner** [martin-volf/elm-jsonrpc#3]
elm 0.19 seems to try to install your package, but throws an error about a corrupted elm.json in list-extra 2.0.0 that seems related.

**Comment by martin-volf** [comment]
[Benoit Anselme's fork](https://github.com/benitoDeLaCasita/elm-jsonrpc) fixes 0.19 compatibility in the branch elm-0.19 - use that one if you are in a hurry, it may take me a while before I get back to it.

**Comment by PixelPartner** [comment]
Thank you very much!
